name: CICD Pipeline Simulation
 
on:
  push:
    branches: [ master ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "Building the application"
 
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests after build"
 
  scanning:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build step
        run: exit 1
       
 
  release:
    needs: [test, scanning]
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests after build"
 
  dev-deployment:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests after build"
 
  dev-testing:
    needs: dev-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests after build"
 
  sit-deployment:
    needs: dev-testing
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests after build"
 
 
  sit-testing:
    needs: sit-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests after build"
 
 
 
  pre-prod-deployment:
    needs: sit-testing
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests after build"
 
 
  pre-prod-testing:
    needs: pre-prod-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests after build"
 
 
  prod-deployment:
    needs: pre-prod-testing
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests after build"
 
  prod-testing:
    needs: prod-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests after build"
 
 
 
 
 
 
