name: CI-CD Pipeline

on: [workflow_dispatch]

jobs:

  validate:
    name: Validate _ Pre-requisites
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate build
        run: echo "Running echo"

  
  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run scan
        run: echo "Running security scan..."

  
  deploy_prerequisites:
    name: Deploy Pre-requisites
    runs-on: ubuntu-latest
    needs: [validate, scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare deployment
        run: echo "Running deploy pre-requisites..."

  
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: deploy_prerequisites   
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "Deploying application..."
